import React from "react";
import {
  CatalogGate,
  CatalogMainLayout,
  CatalogModals,
  CatalogToast,
} from "./catalog/components/index";
import type { CatalogViewProps } from "./catalog/types";
import type { CurseForgeMod } from "../types";
import { useCatalogState } from "./catalog/useCatalogState";

export function CatalogView({
  instances,
  selectedInstanceId,
  onSelectInstance,
  onGoInstances,
  onGoPlay,
  onRefreshInstances,
  onConfirm,
  progressLabel,
  initialProjectType = "mod",
  lockedProjectType,
  title,
  subtitle,
  lockSource,
  hiddenProjectTypes = [],
}: CatalogViewProps) {
  const {
    query,
    setQuery,
    results,
    curseResults,
    selectedProject,
    modpackDetails,
    galleryIndex,
    showFullDescription,
    selectedCurse,
    versions,
    selectedVersionId,
    status,
    loading,
    worlds,
    worldsLoading,
    worldsError,
    selectedWorldId,
    importingDatapack,
    toast,
    modModalRef,
    modCloseRef,
    curseModalRef,
    curseCloseRef,
    modpackModalRef,
    modpackCloseRef,
    source,
    page,
    pageSize,
    index,
    totalHits,
    projectType,
    categories,
    showCategories,
    modpackLoader,
    headerTitle,
    headerSubtitle,
    searchPlaceholder,
    showProjectTabs,
    showSourceToggle,
    requiresInstance,
    eligibleInstances,
    selectedInstance,
    loader,
    projectTypeLabel,
    selectedVersion,
    availableLoaders,
    loaderLabel,
    versionLabel,
    loaderChip,
    versionChip,
    noEligibleInstances,
    gateTitle,
    gateMessage,
    installedProjectIds,
    disabledProjectIds,
    showDetailPanel,
    isModpackModalOpen,
    isModModalOpen,
    isCurseModalOpen,
    gallery,
    galleryCount,
    activeImage,
    modpackPreview,
    showDescriptionToggle,
    progressText,
    isProjectInstalled,
    isProjectDisabled,
    isVersionInstalled,
    installButtonContent,
    showCurseforgeBanner,
    modpackButtonContent,
    installDisabled,
    installDisabledReason,
    datapackImportDisabled,
    datapackImportDisabledReason,
    modpackInstallDisabledReason,
    showCatalogSkeleton,
    showEmptyState,
    emptyTitle,
    emptyMessage,
    instanceInfo,
    toggleCategory,
    clearCategories,
    handleSearch,
    handleSelectProjectType,
    handleSelectSource,
    handleToggleCategories,
    handleModpackLoader,
    handleIndexChange,
    handlePageSizeChange,
    handleClearFilters,
    handleShowPopular,
    handlePrevPage,
    handleNextPage,
    handleGalleryPrev,
    handleGalleryNext,
    handleGallerySelect,
    handleShowFullDescription,
    handleHideFullDescription,
    closeProjectModal,
    closeCurseModal,
    handleSelectProject,
    handleInstall,
    handleImportDatapack,
    handleToastAction,
    setSelectedCurse,
    setSelectedVersionId,
    setSelectedWorldId,
  } = useCatalogState({
    instances,
    selectedInstanceId,
    onSelectInstance,
    onGoInstances,
    onGoPlay,
    onRefreshInstances,
    onConfirm,
    progressLabel,
    initialProjectType,
    lockedProjectType,
    title,
    subtitle,
    lockSource,
  });

  if (noEligibleInstances) {
    return (
      <CatalogGate
        open
        headerTitle={headerTitle}
        gateTitle={gateTitle}
        gateMessage={gateMessage}
        onGoInstances={onGoInstances}
      />
    );
  }

  return (
    <>
      <CatalogMainLayout
        header={{
          headerTitle,
          headerSubtitle,
          requiresInstance,
          eligibleInstances,
          selectedInstance,
          onSelectInstance,
        }}
        tabs={{
          showProjectTabs: source === "modrinth" && showProjectTabs,
          projectType,
          hiddenProjectTypes,
          onSelectProjectType: handleSelectProjectType,
        }}
        toolbar={{
          showSourceToggle,
          source,
          onSelectSource: handleSelectSource,
          projectType,
          showCategories,
          categoriesCount: categories.length,
          onToggleCategories: handleToggleCategories,
          modpackLoader,
          onSelectModpackLoader: handleModpackLoader,
          index,
          onChangeIndex: handleIndexChange,
          pageSize,
          onChangePageSize: handlePageSizeChange,
          instanceInfo,
          searchPlaceholder,
          query,
          onQueryChange: setQuery,
          onSearch: handleSearch,
          loading,
          isSourceLocked: source !== "modrinth",
        }}
        results={{
          source,
          projectType,
          showCategories: source === "modrinth" && projectType === "mod" && showCategories,
          categories,
          onToggleCategory: toggleCategory,
          onClearCategories: clearCategories,
          showCatalogSkeleton,
          showEmptyState,
          emptyTitle,
          emptyMessage,
          onClearFilters: handleClearFilters,
          onShowPopular: handleShowPopular,
          results,
          curseResults,
          selectedProjectId: selectedProject?.project_id || null,
          selectedCurseId: selectedCurse?.id || null,
          onSelectProject: handleSelectProject,
          onSelectCurse: (hit: CurseForgeMod) => setSelectedCurse(hit),
          installedProjectIds,
          disabledProjectIds,
          loaderChip,
          versionChip,
          totalHits,
          page,
          pageSize,
          loading,
          onPrevPage: handlePrevPage,
          onNextPage: handleNextPage,
        }}
        detail={{
          show: showDetailPanel,
          source,
          projectType,
          projectTypeLabel,
          versionLabel,
          loader,
          loaderLabel,
          selectedProject,
          selectedCurse,
          versions,
          selectedVersion,
          selectedVersionId,
          onSelectVersionId: setSelectedVersionId,
          onInstall: handleInstall,
          installDisabled,
          installButtonContent,
          installDisabledReason,
          isProjectInstalled,
          isProjectDisabled,
          isVersionInstalled,
        }}
        showDetailPanel={showDetailPanel}
        showCurseforgeBanner={showCurseforgeBanner}
        status={status}
      />

      <CatalogToast toast={toast} onAction={handleToastAction} />

      <CatalogModals
        modrinth={{
          open: isModModalOpen,
          selectedProject,
          projectType,
          projectTypeLabel,
          versionLabel,
          loader,
          loaderLabel,
          selectedVersion,
          availableLoaders,
          versions,
          selectedVersionId,
          onSelectVersionId: setSelectedVersionId,
          worlds,
          worldsLoading,
          worldsError,
          selectedWorldId,
          onSelectWorldId: setSelectedWorldId,
          importingDatapack,
          datapackImportDisabled,
          datapackImportDisabledReason,
          onImportDatapack: handleImportDatapack,
          onInstall: handleInstall,
          installDisabled,
          installButtonContent,
          isProjectInstalled,
          isProjectDisabled,
          isVersionInstalled,
          onClose: closeProjectModal,
          modalRef: modModalRef,
          closeRef: modCloseRef,
        }}
        curseforge={{
          open: isCurseModalOpen,
          selectedCurse,
          showCurseforgeBanner,
          onClose: closeCurseModal,
          modalRef: curseModalRef,
          closeRef: curseCloseRef,
        }}
        modpack={{
          open: isModpackModalOpen,
          selectedProject,
          projectTypeLabel,
          versionLabel,
          activeImage,
          gallery,
          galleryCount,
          galleryIndex,
          onPrevImage: handleGalleryPrev,
          onNextImage: handleGalleryNext,
          onSelectImage: handleGallerySelect,
          modpackDetails,
          showFullDescription,
          modpackPreview,
          showDescriptionToggle,
          onShowFullDescription: handleShowFullDescription,
          onHideFullDescription: handleHideFullDescription,
          versions,
          selectedVersion,
          selectedVersionId,
          onSelectVersionId: setSelectedVersionId,
          loaderLabel,
          onInstall: handleInstall,
          modpackButtonContent,
          modpackInstallDisabledReason,
          loading,
          progressText,
          onClose: closeProjectModal,
          modalRef: modpackModalRef,
          closeRef: modpackCloseRef,
        }}
      />
    </>
  );
}
